- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
    check:
      jobs:
        - training-labs-scripts
    gate:
      jobs:
        - training-labs-scripts

    post:
      jobs:
        - publish-training-labs-scripts
- job:
    name: training-labs-scripts
    description: |
      Build scripts for training-labs repository.
    parent: unittests
    run: playbooks/scripts/run.yaml
